name: 04-workflow-actions

"on": push

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3
            - name: Printing Folders
              run: ls
        # 0. c heckout our code from repository
        # 1. install deps of our react app
        # 2. execute automated tests